### ISSUE TITLE
[FEAT] MSA 서비스 내 로그 데이터 수집 및 분석 파이프라인 구축

### ISSUE THREAD

**Issue by EeeasyCode** [TEAM-YOAJUNG/backend-server#23]
### 작업 사항

현재 저희 서비스의 로그 데이터 수집 및 분석 파이프라인 구축은 Elastic APM 로 구현될 예정입니다.
이에 대한 파이프라인 구축 논의가 필요합니다.

관련 작업자
@EeeasyCode @opp-13 

### 작업 상세 내용

- [x] Elastic APM 구축 논의
- [x] Elastic APM Agent 설치 및 적용
- [x] Elastic APM 모니터링 구현

**Comment by opp-13** [comment]
비슷합니다, 다만 APM Agent는 같은 Container에 배포됩니다.

**Comment by opp-13** [comment]
아래는 오늘 테스트로 만든 dockerFile인데 이 부분만 참고하셔서 도커 빌드 하시면 자동으로 수집 됩니다. 나머지 설정은 elastic에서 처리하면 됩니다.
{placeholder} 처리한 부분은 저희 elastic apm 설정 완료 되면 드리겠습니다.

<pre>
<code>
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY /jarFiles /app

COPY --from=docker.elastic.co/observability/apm-agent-java:latest /usr/agent/elastic-apm-agent.jar /app/elastic-apm-agent.jar

CMD java -javaagent:/app/elastic-apm-agent.jar \
    -Delastic.apm.service_name={서비스 이름} \
    -Delastic.apm.secret_token={placeholder} \
    -Delastic.apm.server_url=https://34.47.85.50:8200 \
    -Delastic.apm.environment={environment 이름 -> 연관된 서비스들을 묶는 단위라고 생각하시면 됩니다.} \
    -Delastic.apm.application_packages=org.example \
    -Delastic.apm.verify_server_cert=false \
    -Delastic.apm.secret_token={placeholder}\
    -jar testApm-0.0.1-SNAPSHOT.jar
</code>
</pre>

**Comment by opp-13** [comment]
아래는 오늘 테스트로 만든 dockerFile인데 이 부분만 참고하셔서 도커 빌드 하시면 자동으로 수집 됩니다. 나머지 설정은 elastic에서 처리하면 됩니다.
{placeholder} 처리한 부분은 저희 elastic apm 설정 완료 되면 드리겠습니다.

<pre>
<code>
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY /jarFiles /app

COPY --from=docker.elastic.co/observability/apm-agent-java:latest /usr/agent/elastic-apm-agent.jar /app/elastic-apm-agent.jar

CMD java -javaagent:/app/elastic-apm-agent.jar \
    -Delastic.apm.service_name={서비스 이름} \
    -Delastic.apm.secret_token={placeholder} \
    -Delastic.apm.server_url={placeholder} \
    -Delastic.apm.environment={environment 이름 -> 연관된 서비스들을 묶는 단위라고 생각하시면 됩니다.} \
    -Delastic.apm.application_packages=org.example \
    -Delastic.apm.verify_server_cert=false \
    -Delastic.apm.secret_token={placeholder}\
    -jar testApm-0.0.1-SNAPSHOT.jar
</code>
</pre>

**Comment by EeeasyCode** [comment]
네, 감사합니다! 
@opp-13 
정확하게 다시 정리해보자면 저희가 ElasticAPM을 사용함으로써,
- 분산 서비스 로그 데이터 중앙화
- 분산 서비스 간 트랜잭션 로그 데이터 중앙화
- 성능 지표 분석

정도가 있는 것 같은데, 또 있을까요?

**Comment by opp-13** [comment]
APM에서는 더 없을 듯 합니다.

**Comment by EeeasyCode** [comment]
답변해주셔서 감사합니다!~
